# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-taranispip-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:

  ## conda-forge packages
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  # TODO nf-core: Add required software dependencies here

  
  
  ## bioconda packages  
  ## common
  - bioconda::fastqc=0.11.8
  #- bioconda::parallel-fastq-dump=0.6.6
  #- bioconda::sra-tools=2.10.7
  - bioconda::fastp=0.20.1
  #- bioconda::samtools=1.9
  #- bioconda::bedtools=2.29.2
  - bioconda::multiqc=1.7  
  
  
  ## assembly
  - bioconda::unicycler=0.4.7
  - bioconda::quast=5.0.2
  - bioconda::bandage=0.8.1
  
  ## analyze schema
  - 
  -
  
  
  ## reference alleles
  - mash
  - blast
  - makeblastdb
  
  ## allele calling
  - blast
  - makeblastdb
  - prodigal
  - prokka

